run-name: Build Spout-gd Extension
on: push
jobs:
  build:
    name: Build library
    runs-on: windows-latest
    strategy:
      matrix:
        release: ['template_debug', 'template_release']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - id: caches
      run: |
        echo "spout_version=$(git rev-parse HEAD:Spout2)" >> $GITHUB_OUTPUT
    - name: Cache Spout build
      id: cache
      uses: actions/cache@v4
      with:
        key: ${{ steps.caches.outputs.spout_version }}
        path: ${{github.workspace}}/Spout2/Binaries/x64
    - name: Install cmake
      uses: lukka/get-cmake@fix-issue-123
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install scons
      run: pip install scons
    - name: Build Spout Library
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: Spout2
      run: |
        cmake -DSKIP_INSTALL_ALL=OFF -DSKIP_INSTALL_HEADERS=OFF -DSKIP_INSTALL_LIBRARIES=OFF -DSPOUT_BUILD_LIBRARY=ON --fresh .
        cmake --build . --clean-first
    - name: Build spout-gd extension
      run: scons target=${{ matrix.release }}
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: spout_gd.windows.${{ matrix.release }}.dll
        path: out/spout_gd.windows.${{ matrix.release }}.dll
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: SpoutLibrary.dll
        path: Spout2/Binaries/x64/SpoutLibrary.dll
      
  release:
    name: Release Library
    runs-on: windows-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: save artifact
      uses: actions/download-artifact@v4
      with:
        merge-multiple: true      
    - name: prepare for packaging
      run: |
        mkdir artifact\addons\spout-gd
        copy spout_gd.windows.template_release.dll artifact\addons\spout-gd
        copy spout_gd.windows.template_debug.dll artifact\addons\spout-gd
        copy SpoutLibrary.dll artifact\addons\spout-gd
        copy spout_gd.gdextension artifact\addons\spout-gd
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: spout-gd.zip
        path: artifact
    - name: push release
      uses: ncipollo/release-action@v1
      with:
        artifacts: spout-gd.zip
