run-name: Build Spout-gd Extension
on: push
jobs:
  build:
    name: Build library
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install cmake
      uses: lukka/get-cmake@fix-issue-123
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install scons
      run: pip install scons
    - name: Build Spout Library
      working-directory: Spout2
      run: |
        cmake -DSKIP_INSTALL_ALL=OFF -DSKIP_INSTALL_HEADERS=OFF -DSKIP_INSTALL_LIBRARIES=OFF -DSPOUT_BUILD_LIBRARY=ON --fresh .
        cmake --build . --clean-first
    - name: Build spout-gd extension (Debug)
      run: scons target=template_debug
    - name: Build spout-gd extension (Release)
      run: scons target=template_release
    - name: prepare for packaging
      run: |
        mkdir artifact\addons\spout-gd
        copy out/spout_gd.windows.template_release.dll artifact\addons\spout-gd
        copy out/spout_gd.windows.template_debug.dll artifact\addons\spout-gd
        copy Spout2/Binaries/x64/SpoutLibrary.dll artifact\addons\spout-gd
        copy spout_gd.gdextension artifact\addons\spout-gd
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: spout-gd.zip
        path: artifact
    - name: push release
      uses: ncipollo/release-action@v1
      if: ${{ github.ref == 'refs/heads/main' }}
      with:
        artifacts: spout-gd.zip
