run-name: Build Spout-gd Extension
on: push
jobs:
  build:
    name: Build library
    runs-on: windows-latest
    strategy:
      matrix:
        release: ['template_debug', 'template_release']
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Check Spout version
      id: caches
      run: |
        "C:\Program Files\Git\bin\git.exe" rev-parse HEAD:Spout2
        echo "spout_version=$("C:\Program Files\Git\bin\git.exe" rev-parse HEAD:Spout2)" >> $GITHUB_OUTPUT
        echo "gdcpp_version=$("C:\Program Files\Git\bin\git.exe" rev-parse HEAD:godot-cpp)" >> $GITHUB_OUTPUT
    - name: Cache Spout build
      id: cache
      uses: actions/cache@v4
      with:
        key: "${{ steps.caches.outputs.spout_version }}:${{steps.caches.outputs.gdcpp_version}}"
        path: |
          ${{ github.workspace }}/Spout2
          ${{ github.workspace }}/godot-cpp
    - name: Install cmake
      uses: lukka/get-cmake@fix-issue-123
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install scons
      run: pip install scons
    - name: Build Spout Library
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: Spout2
      run: |
        cmake -DSKIP_INSTALL_ALL=OFF -DSKIP_INSTALL_HEADERS=OFF -DSKIP_INSTALL_LIBRARIES=OFF -DSPOUT_BUILD_LIBRARY=ON --fresh .
        cmake --build . --clean-first
    - name: Build spout-gd extension
      run: scons target=${{ matrix.release }}
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: spout2_${{ matrix.release }}
        path: |
          out/spout_gd.windows.${{ matrix.release }}.dll
          Spout2/Binaries/x64/SpoutLibrary.dll
          spout_gd.gdextension
      
  release:
    name: Release Library
    needs: [build]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: load artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts
        merge-multiple: true      
    - name: prepare for packaging
      run: |
        mkdir release\addons\spout-gd
        copy artifacts/spout_gd.windows.template_release.dll release\addons\spout-gd
        copy artifacts/spout_gd.windows.template_debug.dll release\addons\spout-gd
        copy artifacts/SpoutLibrary.dll release\addons\spout-gd
        copy artifacts/spout_gd.gdextension release\addons\spout-gd
    - name: save artifact
      uses: actions/upload-artifact@v3
      with:
        name: spout-gd.zip
        path: artifact
    - name: push release
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: spout-gd.zip
